lib/notebookgarden_web/router.ex
defmodule NotebookGardenWeb.Router do
  use NotebookGardenWeb, :router

  import NotebookGardenWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {NotebookGardenWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NotebookGardenWeb do
    pipe_through :browser

    get "/", PageController, :index

    live "/notebooks", NotebookLive.Index, :index
    live "/notebooks/new", NotebookLive.Index, :new
    live "/notebooks/:id/edit", NotebookLive.Index, :edit

    live "/notebooks/:id", NotebookLive.Show, :show
    live "/notebooks/:id/show/edit", NotebookLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", NotebookGardenWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NotebookGardenWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", NotebookGardenWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", NotebookGardenWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", NotebookGardenWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/notebookgarden_web/live/live_helpers.ex
defmodule NotebookGardenWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `NotebookGardenWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal NotebookGardenWeb.NotebookLive.FormComponent,
        id: @notebook.id || :new,
        action: @live_action,
        notebook: @notebook,
        return_to: Routes.notebook_index_path(@socket, :index) %>
  """
  def live_modal(component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(NotebookGardenWeb.ModalComponent, modal_opts)
  end
end

lib/notebookgarden_web/live/modal_component.ex
defmodule NotebookGardenWeb.ModalComponent do
  use NotebookGardenWeb, :live_component

  @impl true
  def render(assigns) do
    ~H"""
    <div
      id={@id}
      class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target={@myself}
      phx-page-loading
      class="bg-white shadow sm:rounded-lg">

      <div class="px-4 py-5 sm:p-6">
        <%= live_component @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/notebookgarden_web/live/notebook_live/form_component.ex
defmodule NotebookGardenWeb.NotebookLive.FormComponent do
  use NotebookGardenWeb, :live_component

  alias NotebookGarden.Coding

  @impl true
  def update(%{notebook: notebook} = assigns, socket) do
    changeset = Coding.change_notebook(notebook)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"notebook" => notebook_params}, socket) do
    changeset =
      socket.assigns.notebook
      |> Coding.change_notebook(notebook_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"notebook" => notebook_params}, socket) do
    save_notebook(socket, socket.assigns.action, notebook_params)
  end

  defp save_notebook(socket, :edit, notebook_params) do
    case Coding.update_notebook(socket.assigns.notebook, notebook_params) do
      {:ok, _notebook} ->
        {:noreply,
         socket
         |> put_flash(:info, "Notebook updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_notebook(socket, :new, notebook_params) do
    case Coding.create_notebook(notebook_params) do
      {:ok, _notebook} ->
        {:noreply,
         socket
         |> put_flash(:info, "Notebook created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/notebookgarden_web/live/notebook_live/index.ex
defmodule NotebookGardenWeb.NotebookLive.Index do
  use NotebookGardenWeb, :live_view

  alias NotebookGarden.Coding
  alias NotebookGarden.Coding.Notebook

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :notebooks, list_notebooks())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Notebook")
    |> assign(:notebook, Coding.get_notebook!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Notebook")
    |> assign(:notebook, %Notebook{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Notebooks")
    |> assign(:notebook, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    notebook = Coding.get_notebook!(id)
    {:ok, _} = Coding.delete_notebook(notebook)

    {:noreply, assign(socket, :notebooks, list_notebooks())}
  end

  defp list_notebooks do
    Coding.list_notebooks()
  end
end

lib/notebookgarden_web/live/notebook_live/show.ex
defmodule NotebookGardenWeb.NotebookLive.Show do
  use NotebookGardenWeb, :live_view

  alias NotebookGarden.Coding

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:notebook, Coding.get_notebook!(id))}
  end

  defp page_title(:show), do: "Show Notebook"
  defp page_title(:edit), do: "Edit Notebook"
end

lib/notebookgarden_web/live/notebook_live/form_component.html.heex
<div class="px-4 py-5 sm:p-6">
  <h3 class="text-lg leading-6 font-medium text-gray-900">
    <%= @title %>
  </h3>

  <.form
    let={f}
    for={@changeset}
    id="notebook-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">


    <div class="mt-2 max-w-xl text-sm text-gray-500">
      <%= label f, :title, class: "sr-only" %>
      <%= text_input f, :title, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
      <%= error_tag f, :title %>
    </div>

    <div class="mt-5">
      <%= submit "Save", phx_disable_with: "Saving...", class: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:text-sm" %>
    </div>
  </.form>
</div>

lib/notebookgarden_web/live/notebook_live/index.html.heex
<h1>Listing Notebooks</h1>

<%= if @live_action in [:new, :edit] do %>
  <%= live_modal NotebookGardenWeb.NotebookLive.FormComponent,
    id: @notebook.id || :new,
    title: @page_title,
    action: @live_action,
    notebook: @notebook,
    return_to: Routes.notebook_index_path(@socket, :index) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="notebooks">
    <%= for notebook <- @notebooks do %>
      <tr id={"notebook-#{notebook.id}"}>
        <td><%= notebook.title %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.notebook_show_path(@socket, :show, notebook) %></span>
          <span><%= live_patch "Edit", to: Routes.notebook_index_path(@socket, :edit, notebook) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: notebook.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Notebook", to: Routes.notebook_index_path(@socket, :new) %></span>

lib/notebookgarden_web/live/notebook_live/show.html.heex
<h1>Show Notebook</h1>

<%= if @live_action in [:edit] do %>
  <%= live_modal NotebookGardenWeb.NotebookLive.FormComponent,
    id: @notebook.id,
    title: @page_title,
    action: @live_action,
    notebook: @notebook,
    return_to: Routes.notebook_show_path(@socket, :show, @notebook) %>
<% end %>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @notebook.title %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.notebook_show_path(@socket, :edit, @notebook), class: "button" %></span> |
<span><%= live_redirect "Back", to: Routes.notebook_index_path(@socket, :index) %></span>